import { Banks } from "../types/datas.typings";

export const Bank: Banks[] = [
  { id: "1", name: "State Bank of India" },
  { id: "2", name: "Indian Bank" },
  { id: "3", name: "Indian Overseas Bank" },
  { id: "4", name: "Canara Bank" },
  { id: "5", name: "Bank of Baroda" },
  { id: "6", name: "Punjab National Bank" },
  { id: "7", name: "Union Bank of India" },
  { id: "8", name: "Bank of India" },
  { id: "9", name: "Central Bank of India" },
  { id: "10", name: "Bank of Maharashtra" },
  { id: "11", name: "HDFC Bank" },
  { id: "12", name: "ICICI Bank" },
  { id: "13", name: "Axis Bank" },
  { id: "14", name: "Kotak Mahindra Bank" },
  { id: "15", name: "IndusInd Bank" },
  { id: "16", name: "Yes Bank" },
  { id: "17", name: "IDFC FIRST Bank" },
  { id: "18", name: "Federal Bank" },
  { id: "19", name: "South Indian Bank" },
  { id: "20", name: "RBL Bank" },
  { id: "21", name: "Karur Vysya Bank" },
  { id: "22", name: "City Union Bank" },
  { id: "23", name: "Tamilnad Mercantile Bank" },
  { id: "24", name: "Tamil Nadu Grama Bank" },
  { id: "25", name: "TNSC Bank" },
  { id: "26", name: "Equitas Small Finance Bank" },
  { id: "27", name: "Ujjivan Small Finance Bank" },
  { id: "28", name: "AU Small Finance Bank" },
  { id: "29", name: "Jana Small Finance Bank" },
  { id: "30", name: "ESAF Small Finance Bank" },
  { id: "31", name: "Standard Chartered Bank" },
  { id: "32", name: "Citibank" },
  { id: "33", name: "HSBC" },
  { id: "34", name: "Deutsche Bank" },
  { id: "35", name: "BNP Paribas" },
  { id: "36", name: "CSB Bank" },
  { id: "37", name: "DCB Bank" },
  { id: "38", name: "Bandhan Bank" },
  { id: "39", name: "Dhanalakshmi Bank" },
  { id: "40", name: "DBS Bank India" },
  { id: "41", name: "Tamil Nadu State Cooperative Bank" },
  { id: "42", name: "Chennai Central Cooperative Bank" },
  { id: "43", name: "Coimbatore District Cooperative Bank" },
  { id: "44", name: "Madurai District Cooperative Bank" },
  { id: "45", name: "Salem District Cooperative Bank" },
  { id: "46", name: "IDBI Bank" },
  { id: "47", name: "UCO Bank" },
  { id: "48", name: "Punjab and Sind Bank" },
  { id: "49", name: "Nainital Bank" },
  { id: "50", name: "Bank of America" },
];